export const TEST = 'TEST';
export const GET_ALL_GAME_LIST = 'GET_ALL_GAME_LIST'; //获取课件list && gameId FList
export const GET_DATA_JSON = 'GET_DATA_JSON'; //获取游戏资源信息
export const TOGGLE_LOADING = 'TOGGLE_LOADING'; //获取游戏资源信息
export const UPDATE_QUESTION_SORT = 'UPDATE_QUESTION_SORT'; //'更新游戏信息排序'
export const ADD_QUESTION_TEMPLATE = 'ADD_QUESTION_TEMPLATE'; //更新游戏信息排序
export const UPD_QUESTION_ANSWER_SCORE = 'SET_QUESTION_SCORE'; //设置题目分值
export const UPD_QUESTION_ANSWER_INFO = 'UPD_QUESTION_ANSWER_INFO'; //设置游戏正误
export const UPD_QUESTION_ANSWER_IMG = 'UPD_QUESTION_ANSWER_IMG'; //设置游戏答案图片信息
export const UPD_QUESTION_ANSWER_MP3 = 'UPD_QUESTION_ANSWER_MP3'; //设置游戏答案音频信息
export const SELECT_IMG = 'SELECT_IMG'; //选择图片资源
export const UPD_GAME_RES_TABLE = 'UPD_GAME_RES_TABLE'; //获取游戏资源列表结构
export const UPD_GAME_RES_JSON = 'UPD_GAME_RES_JSON'; //获取游戏资源列表结构
export const TEMP_EDIT = 'TEMP_EDIT'; //临时保存编辑数据
